version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.22.0
    - 7.23.0
