name: Audit pull request
on: [pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify Deploy Preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'https://deploy-preview-${{ github.event.number }}--krutsch.netlify.com/'
